#!/usr/bin/env python3
"""Generate documentation from verified sources.

Inputs:
  implementation-status.json  — capability status (checked by CI)
  benchmarks/results/*.json   — measured benchmark reports

Outputs:
  docs/STATUS.md              — capability tables grouped by maturity
  docs/BENCHMARKS.md          — benchmark tables per environment
  README.md                   — the section between the GENERATED markers

Run:  python3 scripts/generate-docs.py [--check]
With --check, exits non-zero if any output file would change (CI gate).
"""

import glob
import json
import sys

STATUS_ORDER = {"implemented": 0, "partial": 1, "absent": 2}
BEGIN = "<!-- BEGIN GENERATED: capability-summary (scripts/generate-docs.py) -->"
END = "<!-- END GENERATED: capability-summary -->"


def load_status():
    with open("implementation-status.json") as f:
        return json.load(f)


def maturity(cap):
    # Everything working is experimental until 1.0; absent capabilities are
    # planned or rejected.
    if cap["status"] in ("implemented", "partial"):
        return "Experimental"
    return "Planned / absent"


def fmt_list(items, empty="—"):
    if not items:
        return empty
    return "; ".join(items)


def status_md(data):
    lines = [
        "# Implementation status",
        "",
        "Generated by `scripts/generate-docs.py` from",
        "[`implementation-status.json`](../implementation-status.json).",
        "Do not edit by hand; CI fails if this file is stale.",
        "",
        f"Status file phase: {data['updated_for_phase']}.",
        "",
        "There is no **Stable** tier: the crate is pre-1.0 and every working",
        "capability is Experimental by policy. 1.0.0 requires stable APIs and",
        "reproducible guarantees.",
        "",
    ]
    groups = {}
    for cap in data["capabilities"]:
        groups.setdefault(maturity(cap), []).append(cap)
    for group in ["Experimental", "Planned / absent"]:
        caps = groups.get(group, [])
        if not caps:
            continue
        caps.sort(key=lambda c: (STATUS_ORDER[c["status"]], c["capability"]))
        lines += [f"## {group}", ""]
        lines.append(
            "| Capability | Status | Implementation | Correctness tests | Benchmarks | Verification | Limitations |"
        )
        lines.append("|---|---|---|---|---|---|---|")
        for c in caps:
            lines.append(
                "| {} | {} | {} | {} | {} | {} | {} |".format(
                    c["capability"],
                    c["status"],
                    fmt_list(c.get("implementation_files", [])),
                    fmt_list(c.get("correctness_tests", [])),
                    fmt_list(c.get("benchmarks", [])),
                    fmt_list(c.get("verification", [])),
                    c.get("notes", "—").replace("|", "/"),
                )
            )
        lines.append("")
    return "\n".join(lines) + "\n"


def bench_md():
    lines = [
        "# Measured benchmarks",
        "",
        "Generated by `scripts/generate-docs.py` from the raw JSON in",
        "[`benchmarks/results/`](../benchmarks/results/). Every record was",
        "verified against the scalar reference **before** timing; incorrect",
        "results carry no timings and fail CI. Numbers are only comparable",
        "within one file (one machine, one run).",
        "",
    ]
    for path in sorted(glob.glob("benchmarks/results/*.json")):
        with open(path) as f:
            report = json.load(f)
        env = report["environment"]
        lines += [
            f"## {path.split('/')[-1]}",
            "",
            f"- CPU: {env['cpu']} ({env['arch']}, {env['os']})",
            f"- Selected backend: {env['selected_backend']}",
            f"- Detected features: `{env['detected_features']}`",
            f"- Git commit: `{env['git_commit']}`",
            "",
            "| Workload | Backend | Size | Median | p95 | Samples |",
            "|---|---|---:|---:|---:|---:|",
        ]

        def fmt_ns(ns):
            if ns >= 1_000_000:
                return f"{ns / 1_000_000:.3f} ms"
            if ns >= 1_000:
                return f"{ns / 1_000:.2f} µs"
            return f"{ns} ns"

        for r in report["results"]:
            stats = r["stats"]
            lines.append(
                "| {} | {} | {} | {} | {} | {} |".format(
                    r["workload"],
                    r["backend"],
                    r["size"],
                    fmt_ns(stats["median_ns"]),
                    fmt_ns(stats["p95_ns"]),
                    r["iterations"],
                )
            )
        lines.append("")
    return "\n".join(lines) + "\n"


def readme_section(data):
    counts = {"implemented": 0, "partial": 0, "absent": 0}
    for c in data["capabilities"]:
        counts[c["status"]] += 1
    lines = [
        BEGIN,
        "",
        "### Capability summary (generated)",
        "",
        f"{counts['implemented']} implemented · {counts['partial']} partial · "
        f"{counts['absent']} absent — full detail in [docs/STATUS.md](docs/STATUS.md),",
        "measured numbers in [docs/BENCHMARKS.md](docs/BENCHMARKS.md).",
        "",
        "| Capability | Status |",
        "|---|---|",
    ]
    for c in sorted(
        data["capabilities"], key=lambda c: (STATUS_ORDER[c["status"]], c["capability"])
    ):
        lines.append(f"| {c['capability']} | {c['status']} |")
    lines += ["", END]
    return "\n".join(lines)


def update_readme(data):
    with open("README.md") as f:
        readme = f.read()
    section = readme_section(data)
    if BEGIN in readme:
        start = readme.index(BEGIN)
        end = readme.index(END) + len(END)
        readme = readme[:start] + section + readme[end:]
    else:
        anchor = "## What works today (verified)"
        readme = readme.replace(anchor, section + "\n\n" + anchor, 1)
    return readme


def main():
    check = "--check" in sys.argv
    data = load_status()
    outputs = {
        "docs/STATUS.md": status_md(data),
        "docs/BENCHMARKS.md": bench_md(),
        "README.md": update_readme(data),
    }
    stale = []
    for path, content in outputs.items():
        try:
            with open(path) as f:
                current = f.read()
        except FileNotFoundError:
            current = None
        if current != content:
            stale.append(path)
            if not check:
                with open(path, "w") as f:
                    f.write(content)
    if check:
        if stale:
            print(f"STALE generated docs: {stale}. Run scripts/generate-docs.py")
            sys.exit(1)
        print("generated docs are up to date")
    else:
        print(f"wrote: {list(outputs)} (changed: {stale or 'none'})")


if __name__ == "__main__":
    main()
